// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClhIYspZK8aekjZ4jGULsoqv926k2RyXI',
    appId: '1:65038837534:web:feff1a21d2666dbc574b0f',
    messagingSenderId: '65038837534',
    projectId: 'aquatrack-72b83',
    authDomain: 'aquatrack-72b83.firebaseapp.com',
    storageBucket: 'aquatrack-72b83.firebasestorage.app',
    measurementId: 'G-GPZ86ZFB6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX1BgqnW7eoN9yJkmmefefhyMWNcZ7_7I',
    appId: '1:65038837534:android:dd8a6bb1d05711de574b0f',
    messagingSenderId: '65038837534',
    projectId: 'aquatrack-72b83',
    storageBucket: 'aquatrack-72b83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaoO4PBLtPHKVSear5OistV2tongFJ3Q',
    appId: '1:65038837534:ios:44611c572592d6a1574b0f',
    messagingSenderId: '65038837534',
    projectId: 'aquatrack-72b83',
    storageBucket: 'aquatrack-72b83.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqaoO4PBLtPHKVSear5OistV2tongFJ3Q',
    appId: '1:65038837534:ios:44611c572592d6a1574b0f',
    messagingSenderId: '65038837534',
    projectId: 'aquatrack-72b83',
    storageBucket: 'aquatrack-72b83.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClhIYspZK8aekjZ4jGULsoqv926k2RyXI',
    appId: '1:65038837534:web:cabfda3b5ea95f92574b0f',
    messagingSenderId: '65038837534',
    projectId: 'aquatrack-72b83',
    authDomain: 'aquatrack-72b83.firebaseapp.com',
    storageBucket: 'aquatrack-72b83.firebasestorage.app',
    measurementId: 'G-9ZRT829PCS',
  );
}
